replicaCount: 2

image:
  repository: amichaihadad2206/blizzard-app
  tag: d3b685989de7a3cd838fa7876355833af7e2bd89
  pullPolicy: Always

ingress:
  host: app.blizzard.co.il

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

existingSecret:
  name: openweather-secret
  key: openweather


# AWS configuration
awsAccountId: "163459217187"
awsRegion: "us-east-1"

# AWS Secrets Manager configuration
awsSecretsManager:
  secretArn: "arn:aws:secretsmanager:us-east-1:163459217187:secret:openweather-secret-bVVhb2"

# IAM Creator configuration - needs permission to create IAM roles/policies
iamCreator:
  # This role should already exist and have IAM create permissions
  roleArn: "arn:aws:iam::163459217187:role/eks-cluster-secrets-store-csi-driver"

nodeSelector:
  role: services

tolerations:
- key: "dedicated"
  operator: "Equal"
  value: "services"
  effect: "NoSchedule" 