apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.existingSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.existingSecret.key }}: {{ .Values.apiKeys.openWeatherToken | b64enc }} 