apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-secrets-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Values.awsAccountId }}:role/blizzard-app-secrets-role" 