apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: blizzard-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: blizzard-app
  template:
    metadata:
      name: 'blizzard-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/AmichaiHadad/Blizzardapp.git
        targetRevision: main
        path: 'helm-chart'
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: blizzard-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m 