apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: blizzard-app-aws-secrets
  namespace: blizzard-app
spec:
  provider: aws
  parameters:
    region: us-east-1
    objects: |
      - objectName: "arn:aws:secretsmanager:us-east-1:163459217187:secret:openweather-secret-bVVhb2"
        objectType: "secretsmanager"
        objectVersion: "latest"
        objectAlias: "open-weather-token"
  secretObjects:
    - secretName: openweather-secret
      type: Opaque
      data:
        - objectName: "open-weather-token"
          key: openweather