name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'helm-chart/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'helm-chart/**'

env:
  DOCKER_IMAGE: amichaihadad2206/blizzard-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      id: build-image
      uses: docker/build-push-action@v4
      with:
        context: ./app
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:latest
          ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

    - name: Update Helm chart values with new image tag
      if: github.event_name != 'pull_request'
      run: |
        IMAGE_TAG=latest
        
  